language: python
sudo: required
python:
  - 2.7
  - 3.5
  - 3.6
before_install:
    - sudo apt-get install ghostscript libreoffice
    - echo '/usr/bin/python' > env
#    - sudo VERSION=5.3.1.2 bash ci/linux.bash
#    - make env
install:
    - travis_retry pip install tox tox-travis coveralls
script:
    - tox
notifications:
    email: false
after_success:
  - coveralls
